const TABS = {
  ALL: 'ALL',
  FEATURED: 'FEATURED'
};

const ACTIONS = {
  ADD_TIMELINE: 'ADD_TIMELINE',
  DELETE_TIMELINE: 'DELETE_TIMELINE',
  UPDATE_TIMELINE: 'UPDATE_TIMELINE'
};

const CHANGE = 'CHANGE';

export {TABS, ACTIONS, CHANGE};
