const Tabs = {
  ALL: 'ALL',
  HIGHTLIGHT: 'HIGHTLIGHT'
};

const Actions = {
  ADD_TIMELINE: 'ADD_TIMELINE',
  DELETE_TIMELINE: 'DELETE_TIMELINE',
  UPDATE_TIMELINE: 'UPDATE_TIMELINE'
};

export {Tabs, Actions};
